import { Navbar } from '@/Components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Providers from '@/Components/Provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Dine market',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Navbar />
          <main>
            {children}
          </main>
        </Providers>
      </body>
    </html>
  )
}
